language: cpp

compiler:
  - gcc

os:
  - linux
  
sudo: required
dist: trusty

env:
  - QT_BASE=55

before_install:
  - if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
  - sudo apt-get update -qq

install:
  - if [ "$QT_BASE" = "55" ]; then sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh; fi

script:
  - qmake -r
  - make
  # Check that everything built correctly:
  - make check
  # Now lets execute the app to see that it runs ok:

branches:
  only:
  - master
  
notifications:
  email: false
